name: Deploy back end docker image on AWS EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - '**/*'
      - '!ui/**'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit id as tag
        run: echo "docker_tag=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/echo-box:${{env.docker_tag}}

      - name: Deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            docker stop echo-box || true
            docker rm echo-box || true
            docker rmi $(docker images -q ${{secrets.DOCKER_USERNAME}}/echo-box) || true
            docker pull ${{secrets.DOCKER_USERNAME}}/echo-box:${{env.docker_tag}}
            docker run --network="host" -d --name echo-box -p 8090:8090 ${{secrets.DOCKER_USERNAME}}/echo-box:${{env.docker_tag}}